name: HardcoreLives
version: '${version}'
main: me.jcbasso.hardcorelives.HardcoreLives
api-version: 1.19
authors: [ JuanCruzBasso ]
description: Hardcore with limited amount of lives
website: jc.com.ar
commands:
  lives:
    description: Manage users lives
permissions:
  hardcorelives.*:
    description: Gives access to all /hcl commands
    default: true
    children:
      hardcorelives.get: true
      hardcorelives.set: true
      hardcorelives.revive: true
  hardcorelives.get:
    description: Gives access to /hcl get command
  hardcorelives.set:
    description: Gives access to /hcl set command
  hardcorelives.revive:
    description: Gives access to /hcl revive command